### ISSUE TITLE
Visual Studio Code issue

### ISSUE THREAD

**Issue by lumorer** [elixirbytes/elixir-for-beginners#21]
Hello guys, I installed Visual Studio Code and after many efforts and hrs spent to understand what's going on, I cannot find a solution. Anyone of you ran into a problem as the following one?
I attached also a screenshot.  // Opening the REPL shell, any code typed in properly works. But, the only way to run the code presents in the editor window is selecting the code (by 'Selection' > 'Select all' in the menu), then selecting 'Terminal' > 'Run Selected Text': in this case, code is executed properly in the shell. 
PS the only message I get as I run VSC is the one in the low right corner, an issue regarding mix.
...many thanks for any hint :-)

<img width="1413" alt="screenshot" src="https://user-images.githubusercontent.com/63241958/79080568-52cadb00-7d16-11ea-862e-69668f1f49fb.png">

**Comment by lorenzosinisi** [comment]
Hello @lumorer , if you join the class today we can talk about it there. Otherwise I can help you in writing here, let me know :)

**Comment by lumorer** [comment]
Ciao Lorenzo,

ho visto la tua mail pochi istanti prima il webinar.
In ogni caso, non avrei voluto rubare tempo agli altri.
Se (capisco benissimo che sei impegnato oltremodo) hai la possibilità di
darmi un suggerimento in merito...
In caso contrario, non preoccuparti, vedrò di risolvere in qualche modo.

Grazie mille
Luigi

Il giorno mer 15 apr 2020 alle ore 18:51 Lorenzo Sinisi <
notifications@github.com> ha scritto:
