### ISSUE TITLE
Prefazione - chat

### ISSUE THREAD

**Issue by antonellomangone** [elixirbytes/elixir-for-beginners#9]
Nel documento di prefazione non viene indicata la chat e tutte le informazioni del caso.

**Comment by kpanic** [comment]
@antonellomangone per adesso non stiamo aggiungendo questa informazione per due motivi:

* Non abbiamo ancora trovato un sistema di video conferenze che regga il numero di partecipanti che abbiamo e che rispetti (un minimo) la privacy
* Essendo in due, non so se riusciremmo a gestire altre persone.

Escludendo le informazioni sulla chat, avevi in mente qualcosa'altro?

**Comment by antonellomangone** [comment]
@kpanic per ora non ho in mente altro, magari più avanti mi verrà in mente qualcosa da aggiungere.
